name: webview CI/CD

on:
  push:
    branches: "main"
    paths-ignore:
      - "README.md"

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Make package
        run: npm run make
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: "./**/*[.exe,.deb]"
          retention-days: 1

  publish_release:
    name: Publish to release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Rename linux artifact
        run: find ./ -name "*.deb" -type f -exec mv {} ./webview-linux.deb \;
      - name: Rename windows artifact
        run: find ./ -name "*.exe" -type f -exec mv {} ./webview-windows-setup.exe \;
      - name: Upload artifacts to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./*.deb, ./*.exe"
          tag: v${{ github.run_number }}
