name: Node.js CI

on:
  push:
    branches: "main"
    paths-ignore:
      - "README.md"

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run make
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          name: webview-linux
          path: "/home/runner/work/webview/webview/out/make/deb/x64/*.deb"

  build_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run make
      - run: pwd
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          name: webview-windows
          path: "D:\\a\\webview\\webview\\out\\make\\squirrel.windows\\x64\\*.Setup"
