on:
  push:
    branches: "main"
    paths-ignore:
      - "README.md"

jobs:
  publish_release:
    runs-on: ubuntu-latest
    needs: [build_linux, build_windows]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        # with:
        #   name: site-build
      - name: Display structure of downloaded files
        run: ls
      - name: Create release
        id: new-release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Changes in this Release
              - First Change
              - Second Change
          draft: false
          prerelease: false
      - name: Upload artifacts to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.new-release.outputs.upload_url }}
          asset_path: ./webview-linux.zip
          asset_name: webview-linux.zip
          asset_content_type: application/zip

  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Make package
        run: npm run make
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          name: webview-linux
          path: "/home/runner/work/webview/webview/out/make/deb/x64/*.deb"

  build_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Make package
        run: npm run make
      - name: DEBUG
        run: ls D:\a\webview\webview\out\make\squirrel.windows\
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          name: webview-windows
          path: "D:\\a\\webview\\webview\\out\\make\\squirrel.windows\\x64\\*.Setup"
