on:
  push:
    branches: "main"
    paths-ignore:
      - "README.md"

jobs:
  publish_release:
    name: Publish to release
    runs-on: ubuntu-latest
    needs: [linux_build, windows_build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Rename artifacts
        run: mv ./*/*.deb ./webview-linux.deb && mv ./*/*.exe ./webview-windows.exe
      - name: Upload artifacts to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./*.deb, ./*.exe"
          tag: v${{ github.run_number }}

  linux_build:
    name: Linux build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Make package
        run: npm run make
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          name: webview-linux
          path: "./out/make/deb/x64/*.deb"

  windows_build:
    name: Windows build
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Make package
        run: npm run make
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          name: webview-windows
          path: "./out/make/squirrel.windows/x64/*.exe"
